version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3090:3090"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdatabase
    depends_on:
      - mysql
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdatabase
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: yourpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
      restart_policy:
        condition: on-failure

volumes:
  mysql_data:

networks:
  default:
    driver: overlay

name: Deploy to UpCloud
on:
 push:
   branches:
     - main
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Install sshpass
       run: sudo apt-get install -y sshpass
     - name: Sync files to UpCloud
       env:
         SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
       run: |
         # Disable strict host key checking
         sshpass -p "Vivek1819" rsync -avz --delete --exclude='node_modules' --include='test/example.test.js' -e "ssh -o StrictHostKeyChecking=no" ./ vivek@95.111.219.120:~/Studio-4-project
