name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the action on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx (to build multi-platform images if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Cache Docker layers to speed up the build process
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build --file Dockerfile --tag my-react-app:latest .

      # Log in to Docker Hub (or other Docker registry) to push the image
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker image to the registry
      - name: Push Docker image
        run: |
          docker tag my-react-app:latest your-dockerhub-username/my-react-app:latest
          docker push your-dockerhub-username/my-react-app:latest
