name: Build and Deploy to UpCloud

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the action on pull requests to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          npm cache clean --force
          npm install --legacy-peer-deps
          docker build --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest .

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest

      # Step 7: Install sshpass for deployment
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      # Step 8: Deploy Docker container on UpCloud
      - name: Deploy Docker container on UpCloud
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@95.111.219.120 << EOF
            set -e

            echo "Updating the server..."
            sudo apt update

            echo "Installing Docker if not present..."
            sudo apt install -y docker.io || true

            echo "Logging into Docker Hub..."
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

            echo "Pulling the latest Docker image..."
            docker pull $DOCKER_USERNAME/my-react-app:latest

            echo "Stopping and removing existing container..."
            docker stop my-react-app || true
            docker rm my-react-app || true

            echo "Running the new container..."
            docker run -d --name my-react-app -p 5555:5555 $DOCKER_USERNAME/my-react-app:latest

            echo "Cleaning up unused Docker images..."
            docker image prune -af || true

            echo "Deployment complete!"
          EOF
